# To enable RDP, uncomment the environment and on_finish lines, then run
# xfreerdp /p:notverysecret-butp0licy! /u:appveyor /v:<ip>:<port>

#environment:
#  APPVEYOR_RDP_PASSWORD: notverysecret-butp0licy!
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  matrix:
  - MINGW_DIR: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
  - MINGW_DIR: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin

matrix:
  fast_finish: true

before_build:
- set PATH=%CD%\.local\bin;%MINGW_DIR%;C:\Program Files\Git\mingw64\bin;%PATH%

build_script:
  - mingw32-make debug
  - mingw32-make all
  - mingw32-make package

artifacts:
- path: libsmear-dev_*_*.zip
  name: Smudge Archive

deploy:
  description:
  provider: GitHub
  auth_token:
    secure: /er0LdGqETNhhuXckQ5cq6D3pL2kknM0FISmk9TqHx+iS5GG/uAcrcKLnl5Q/g3d
  on:
    appveyor_repo_tag: true
